name: snowflake-devops-demo

on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Run schemachange with key pair authentication
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SF_PRIVATE_KEY: ${{ secrets.SF_PRIVATE_KEY }}
          SF_KEY_PASSPHRASE: ${{ secrets.SF_KEY_PASSPHRASE }}
        run: |
          echo "Installing schemachange"
          pip install schemachange

          echo "Creating private key file"
          echo "$SF_PRIVATE_KEY" > private_key.p8

          echo "Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/migrations \
            -a $SF_ACCOUNT \
            -u $SF_USERNAME \
            -r $SF_ROLE \
            -w $SF_WAREHOUSE \
            -d $SF_DATABASE \
            -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY \
            --private-key-path private_key.p8 \
            --private-key-passphrase $SF_KEY_PASSPHRASE

          echo "Cleaning up private key file"
          rm private_key.p8
